/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "HPI_IF.h"
#include "HPI_IF_I2C.h"
#include "HPI_IF_PINS.h"
#include "HPI_IF_I2C_PVT.h"
#include "HPI_IF_PVT.h"
#include "HPI_IF_BOOT.h"
#include "EC_INT.h"
#include "EC_INT_aliases.h"
#include "I2C_CFG.h"
#include "I2C_CFG_aliases.h"
#include "Bootloadable_1.h"
#include "PDSS_PORT0_RX_CLK.h"
#include "PDSS_PORT0_TX_CLK.h"
#include "FW_LED.h"
#include "FW_LED_aliases.h"
#include "PDSS_PORT0_SAR_CLK.h"
#include "NCP81239_EN_P1.h"
#include "NCP81239_EN_P1_aliases.h"
#include "I2C_MSTR.h"
#include "I2C_MSTR_I2C.h"
#include "I2C_MSTR_PINS.h"
#include "I2C_MSTR_I2C_PVT.h"
#include "I2C_MSTR_PVT.h"
#include "I2C_MSTR_BOOT.h"
#include "NCP81239_EN_P2.h"
#include "NCP81239_EN_P2_aliases.h"
#include "DP_HPD_P1.h"
#include "DP_HPD_P1_aliases.h"
#include "DP_HPD_P2.h"
#include "DP_HPD_P2_aliases.h"
#include "PDSS_PORTX_REFGEN_CLK.h"
#include "PDSS_PORT0_FILT1_CLK.h"
#include "PDSS_PORT0_SWAP_CLK.h"
#include "HPI_IF_SCBCLK.h"
#include "HPI_IF_sda.h"
#include "HPI_IF_sda_aliases.h"
#include "HPI_IF_scl.h"
#include "HPI_IF_scl_aliases.h"
#include "HPI_IF_SCB_IRQ.h"
#include "I2C_MSTR_SCBCLK.h"
#include "I2C_MSTR_sda.h"
#include "I2C_MSTR_sda_aliases.h"
#include "I2C_MSTR_scl.h"
#include "I2C_MSTR_scl_aliases.h"
#include "I2C_MSTR_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

